----------------- LOGIN_DETAILS -------------
CREATE TABLE IF NOT EXISTS LOGIN_DETAILS(
	ID VARCHAR(100) NOT NULL,
	PASSWD VARCHAR(200) NOT NULL,
	PRIMARY KEY(ID),
	UNIQUE KEY (ID)
);

insert into LOGIN_DETAILS VALUES ('root', '4813494d137e1631bba301d5acab6e7bb7aa74ce1185d456565ef51d737677b2');
commit;

------------ENTITY_TYPE---------------------

CREATE TABLE ENTITY_TYPE (
ID INT NOT NULL,
TYPE VARCHAR(20) NOT NULL
);

ALTER TABLE ENTITY_TYPE ADD PRIMARY KEY(ID);

INSERT INTO ENTITY_TYPE VALUES(1, 'ADMIN');
INSERT INTO ENTITY_TYPE VALUES(2, 'CARE_PROVIDER');
INSERT INTO ENTITY_TYPE VALUES(3, 'PATIENT');
COMMIT;

----------------- EMPLOYEE -------------
CREATE TABLE IF NOT EXISTS EMPLOYEE(
	ID VARCHAR(100) NOT NULL,
	FNAME VARCHAR(100) NOT NULL,
	LNAME VARCHAR(100) NOT NULL,
	DOB DATETIME NOT NULL,
	EMAIL_ID VARCHAR(100) NOT NULL,
	ISPERMANENT BOOLEAN NOT NULL,
	PRIMARY KEY(ID),
	UNIQUE KEY (ID)
);

alter table employee add column status Boolean;
alter table employee add column create_date TimeStamp NOT NULL DEFAULT current_timestamp();
alter table employee add column update_date TimeStamp NOT NULL DEFAULT current_timestamp() ON UPDATE current_timestamp();

insert into EMPLOYEE VALUES ('3266dd0a-af55-4775-979e-e35d1', 'ROOT', 'ROOT', STR_TO_DATE('11-Jan-1992', '%d-%b-%Y'), 'root@gmail.com', TRUE, TRUE, current_timestamp(),current_timestamp());
commit;


----------------- ADMIN -------------
CREATE TABLE IF NOT EXISTS ADMIN(
	ID VARCHAR(100) NOT NULL,
	ANNUAL_SALARY FLOAT NOT NULL,
	PRIMARY KEY(ID),
	UNIQUE KEY (ID),
	CONSTRAINT EMPLOYEE_ID FOREIGN KEY (ID) REFERENCES EMPLOYEE(ID) ON DELETE  CASCADE
);
alter table admin add column create_date TimeStamp NOT NULL DEFAULT current_timestamp();
alter table admin add column update_date TimeStamp NOT NULL DEFAULT current_timestamp() ON UPDATE current_timestamp();

insert into admin VALUES ('3266dd0a-af55-4775-979e-e35d1', 89000, current_timestamp(),current_timestamp());

----------------- CARE_PROVIDER -------------
CREATE TABLE IF NOT EXISTS CARE_PROVIDER(
	ID VARCHAR(100) NOT NULL,
	PER_VISIT_CHARGES FLOAT NOT NULL,
	PRIMARY KEY(ID),
	UNIQUE KEY (ID)
);

alter table admin add column create_date TimeStamp NOT NULL DEFAULT current_timestamp();
alter table admin add column update_date TimeStamp NOT NULL DEFAULT current_timestamp() ON UPDATE current_timestamp();
insert into CARE_PROVIDER VALUES ('3266dd0a-af55-4775-979e', 30, current_timestamp(),current_timestamp());

--------------- AUDIT_TRAIL------------------
create sequence AUDIT_TRAIL_SEQUENCER START WITH 1 INCREMENT BY 1;

CREATE TABLE AUDIT_TYPE (
ID INT NOT NULL,
LABEL VARCHAR(20) NOT NULL,
PRIMARY KEY(ID)
);

INSERT INTO AUDIT_TYPE VALUES(1, 'NAME');
INSERT INTO AUDIT_TYPE VALUES(2, 'CONTACT_INFO');
INSERT INTO AUDIT_TYPE VALUES(3, 'ADDRESS');

CREATE table audit_trail (
	ID INT NOT NULL,
	ENTITY_ID VARCHAR(100) NOT NULL,
	ENTITY_TYPE_ID INT NOT NULL,
	PREVIOUS_VALUE VARCHAR(200),
	NEW_VALUE VARCHAR(200),
	CHANGED_BY VARCHAR(200),
	PRIMARY KEY (ID),
	CONSTRAINT FK_ENTITY_TYPE_ID FOREIGN KEY (ENTITY_TYPE_ID) REFERENCES ENTITY_TYPE(ID),
	CONSTRAINT FK_CHANGED_BY FOREIGN KEY (CHANGED_BY) REFERENCES EMPLOYEE(ID)
);

ALTER TABLE AUDIT_TRAIL ADD COLUMN UPDATED_ON DATETIME;

INSERT INTO audit_trail VALUES (
NEXTVAL(AUDIT_TRAIL_SEQUENCER),
'3266dd0a-af55-4775-979e-e35d1',
1,
'MANIK',
'MANIK JAIN',
'3266dd0a-af55-4775-979e-e35d1',
NOW() );

ALTER TABLE AUDIT_TRAIL ADD COLUMN AUDIT_TYPE INT;
ALTER TABLE AUDIT_TRAIL ADD FOREIGN KEY(AUDIT_TYPE) REFERENCES AUDIT_TYPE(ID);
UPDATE AUDIT_TRAIL SET AUDIT_TYPE=1 WHERE ID=4;

